#!/usr/bin/env python3
"""Generate src/core/width_table.zig from the Unicode Character Database.

Usage: gen_width_table.py <ucd-dir> > src/core/width_table.zig

Emits the set of code points whose East_Asian_Width is Wide or Fullwidth --
i.e. the ones that occupy two cells in a monospace grid.

This replaces three hand-maintained copies of an ad-hoc CJK range list that had
drifted apart in the TypeScript original (wrap.ts twice, Editor.svelte once) and
which omitted CJK Extension B and beyond.
"""
import sys, os

UNICODE_VERSION = "16.0.0"

def main():
    path = os.path.join(sys.argv[1], "EastAsianWidth.txt")
    ranges = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            rng, _, width = line.partition(";")
            width = width.strip()
            if width not in ("W", "F"):
                continue
            rng = rng.strip()
            lo, _, hi = rng.partition("..")
            lo = int(lo, 16)
            hi = int(hi, 16) if hi else lo
            if ranges and lo <= ranges[-1][1] + 1:
                ranges[-1] = (ranges[-1][0], max(ranges[-1][1], hi))
            else:
                ranges.append((lo, hi))

    print("//! Generated by tools/gen_width_table.py -- do not edit by hand.")
    print(f"//! Unicode {UNICODE_VERSION}, East_Asian_Width in {{Wide, Fullwidth}}.")
    print()
    print("pub const Range = struct { lo: u21, hi: u21 };")
    print()
    print("/// Code points that occupy two monospace cells. Sorted by `lo`.")
    print("pub const wide_ranges = [_]Range{")
    for lo, hi in ranges:
        print(f"    .{{ .lo = 0x{lo:04X}, .hi = 0x{hi:04X} }},")
    print("};")

if __name__ == "__main__":
    main()
