#!/usr/bin/env python3
"""Generate src/core/wordchar_table.zig from the Unicode Character Database.

Usage: gen_wordchar_table.py <ucd-dir> > src/core/wordchar_table.zig

Emits the code points with General_Category L* or N* -- the set the TypeScript
original matched with the regex /[\\p{L}\\p{N}_]/u for double-click word
selection.
"""
import sys, os

UNICODE_VERSION = "16.0.0"

def main():
    path = os.path.join(sys.argv[1], "DerivedGeneralCategory.txt")
    ranges = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            rng, _, cat = line.partition(";")
            cat = cat.strip()
            if not cat or cat[0] not in ("L", "N"):
                continue
            rng = rng.strip()
            lo, _, hi = rng.partition("..")
            lo = int(lo, 16)
            hi = int(hi, 16) if hi else lo
            ranges.append((lo, hi))

    ranges.sort()
    merged = []
    for lo, hi in ranges:
        if merged and lo <= merged[-1][1] + 1:
            merged[-1] = (merged[-1][0], max(merged[-1][1], hi))
        else:
            merged.append((lo, hi))

    print("//! Generated by tools/gen_wordchar_table.py -- do not edit by hand.")
    print(f"//! Unicode {UNICODE_VERSION}, General_Category in {{L*, N*}}.")
    print()
    print("pub const Range = struct { lo: u21, hi: u21 };")
    print()
    print("/// Letters and numbers, sorted by `lo`.")
    print("pub const word_ranges = [_]Range{")
    for lo, hi in merged:
        print(f"    .{{ .lo = 0x{lo:04X}, .hi = 0x{hi:04X} }},")
    print("};")

if __name__ == "__main__":
    main()
