#!/usr/bin/env python3
"""Generate src/core/grapheme_table.zig from the Unicode Character Database.

Usage: gen_grapheme_table.py <ucd-dir> > src/core/grapheme_table.zig

<ucd-dir> must contain GraphemeBreakProperty.txt, emoji-data.txt and
DerivedCoreProperties.txt from the same UCD release. Re-run this when bumping
the Unicode version; the output is committed so building needs no network.
"""
import sys, os, re

UNICODE_VERSION = "16.0.0"

GB_PROPS = [
    "CR", "LF", "Control", "Extend", "ZWJ", "Regional_Indicator",
    "Prepend", "SpacingMark", "L", "V", "T", "LV", "LVT",
]
ZIG_NAME = {
    "CR": "cr", "LF": "lf", "Control": "control", "Extend": "extend",
    "ZWJ": "zwj", "Regional_Indicator": "regional_indicator",
    "Prepend": "prepend", "SpacingMark": "spacing_mark",
    "L": "l", "V": "v", "T": "t", "LV": "lv", "LVT": "lvt",
}

def parse(path, wanted):
    """Yield (lo, hi, value) for lines whose property field is in `wanted`."""
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            fields = [p.strip() for p in line.split(";")]
            if len(fields) < 2:
                continue
            value = fields[-1] if fields[1] == "InCB" else fields[1]
            if value not in wanted:
                continue
            rng = fields[0]
            if ".." in rng:
                lo, hi = rng.split("..")
            else:
                lo = hi = rng
            yield int(lo, 16), int(hi, 16), value

def coalesce(ranges):
    """Sort by start and merge adjacent/overlapping ranges of equal value."""
    ranges = sorted(ranges)
    out = []
    for lo, hi, val in ranges:
        if out and out[-1][2] == val and lo <= out[-1][1] + 1:
            out[-1] = (out[-1][0], max(out[-1][1], hi), val)
        else:
            out.append((lo, hi, val))
    return out

def emit_table(name, ranges, value_expr, doc):
    print(f"/// {doc}")
    print(f"pub const {name} = [_]Range{{")
    for lo, hi, val in ranges:
        print(f"    .{{ .lo = 0x{lo:04X}, .hi = 0x{hi:04X}, .value = {value_expr(val)} }},")
    print("};")
    print()

def main():
    ucd = sys.argv[1]
    gb = coalesce(parse(os.path.join(ucd, "GraphemeBreakProperty.txt"), set(GB_PROPS)))
    pict = coalesce(parse(os.path.join(ucd, "emoji-data.txt"), {"Extended_Pictographic"}))
    incb = coalesce(parse(os.path.join(ucd, "DerivedCoreProperties.txt"),
                          {"Consonant", "Linker", "Extend"}))
    # All three InCB values are kept. InCB=Extend is *not* simply gcb=Extend
    # plus ZWJ -- it excludes some of them -- so GB9c's walk must consult the
    # real property rather than approximating it.

    print("//! Generated by tools/gen_grapheme_table.py -- do not edit by hand.")
    print(f"//! Unicode {UNICODE_VERSION}.")
    print()
    print("/// Grapheme_Cluster_Break property values (UAX #29 table 2).")
    print("pub const Prop = enum(u8) {")
    print("    none,")
    for p in GB_PROPS:
        print(f"    {ZIG_NAME[p]},")
    print("};")
    print()
    print("/// Indic_Conjunct_Break values relevant to GB9c.")
    print("pub const Incb = enum(u8) { none, consonant, extend, linker };")
    print()
    print("pub fn Range(comptime V: type) type {")
    print("    return struct { lo: u21, hi: u21, value: V };")
    print("}")
    print()

    def table(name, ranges, vtype, vexpr, doc):
        print(f"/// {doc}")
        print(f"pub const {name} = [_]Range({vtype}){{")
        for lo, hi, val in ranges:
            print(f"    .{{ .lo = 0x{lo:04X}, .hi = 0x{hi:04X}, .value = {vexpr(val)} }},")
        print("};")
        print()

    table("gb_ranges", gb, "Prop", lambda v: "." + ZIG_NAME[v],
          "Grapheme_Cluster_Break ranges, sorted by `lo`.")
    table("pict_ranges", pict, "void", lambda v: "{}",
          "Extended_Pictographic ranges, sorted by `lo`.")
    table("incb_ranges", incb, "Incb", lambda v: "." + v.lower(),
          "Indic_Conjunct_Break ranges, sorted by `lo`.")

if __name__ == "__main__":
    main()
